name: CI

on: [push, pull_request]

jobs:
  test:
    name: Node.js v${{ matrix.nodejs }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nodejs: [14]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.nodejs }}

    - name: Install
      run: |
        npm install
        npm install -g nyc

    - name: Compiles
      run: npm run build

    - name: Test w/ Coverage
      run: nyc --include=src npm test

    # - name: Report
    #   if: matrix.nodejs >= 14
    #   run: |
    #     nyc report --reporter=text-lcov > coverage.lcov
    #     bash <(curl -s https://codecov.io/bash)
    #   env:
    #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
