name: CI

on: [push, pull_request]

jobs:
  test:
    name: Node.js v16
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: (env) pnpm
      run: curl -L https://pnpm.js.org/pnpm.js | node - add --global pnpm

    - name: Install
      run: pnpm install

    - name: Compile
      run: pnpm run build

    - name: Test
      run: pnpm run test
